;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.BuyFood",DevComment="")
+GameplayTagList=(Tag="Action.Coffee",DevComment="")
+GameplayTagList=(Tag="Action.DrinkCoffee",DevComment="")
+GameplayTagList=(Tag="Action.Eat",DevComment="")
+GameplayTagList=(Tag="Action.Idle",DevComment="")
+GameplayTagList=(Tag="Action.OrderFood",DevComment="")
+GameplayTagList=(Tag="Action.Relax",DevComment="")
+GameplayTagList=(Tag="Action.ServeCustomer",DevComment="")
+GameplayTagList=(Tag="Action.Sit",DevComment="")
+GameplayTagList=(Tag="Action.Sleep",DevComment="")
+GameplayTagList=(Tag="Action.Talk",DevComment="")
+GameplayTagList=(Tag="Action.Travel",DevComment="")
+GameplayTagList=(Tag="Action.VisitFriend",DevComment="")
+GameplayTagList=(Tag="Action.Work",DevComment="")
+GameplayTagList=(Tag="Need.Caffeine",DevComment="")
+GameplayTagList=(Tag="Need.Energy",DevComment="")
+GameplayTagList=(Tag="Need.Hunger",DevComment="")
+GameplayTagList=(Tag="Need.Money",DevComment="")
+GameplayTagList=(Tag="Need.Social",DevComment="")
+GameplayTagList=(Tag="Type.Apartment",DevComment="")
+GameplayTagList=(Tag="Type.Bar",DevComment="")
+GameplayTagList=(Tag="Type.Cafe",DevComment="")
+GameplayTagList=(Tag="Type.CafeSeat",DevComment="")
+GameplayTagList=(Tag="Type.Chair",DevComment="")
+GameplayTagList=(Tag="Type.CoffeeMachine",DevComment="")
+GameplayTagList=(Tag="Type.Home",DevComment="")
+GameplayTagList=(Tag="Type.Industrial",DevComment="")
+GameplayTagList=(Tag="Type.Office",DevComment="")
+GameplayTagList=(Tag="Type.Park",DevComment="")
+GameplayTagList=(Tag="Type.ParkBench",DevComment="")
+GameplayTagList=(Tag="Type.Plaza",DevComment="")
+GameplayTagList=(Tag="Type.Shop",DevComment="")
+GameplayTagList=(Tag="Type.Table",DevComment="")

